### ISSUE TITLE
Hypercat compliance

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox_directory#2]
It seems to me that (as Mac had already alluded to) that using the hypercat standard for discovery could cover all the needs here and also lower the barrier to entry for developers (no need to figure out another API since there already are hypercat libs https://hypercatiot.github.io/#implementations). If the directory service provided a hypercat catalogue, then with each driver as an item (and 1-1 sensor-driver):

> Vendors of sensors

Item metadata rel + value (i-object-metadata)

> Datastores for sensor drivers

Item metadata rel + value (i-object-metadata)

> Drivers for sensors

Assuming this means getting drivers by sensor type, then simple search functionality of hypercat

> Controllers for actuating drivers

Hypercat catalogues can be nested, so all items can have a ref to the driver host, and that in turn can have it's own catalogue at "/cat" as per hypercat specs. This could replace old adhoc specs like API listings through OPTION requests (like here https://github.com/me-box/databox-twitter-driver/blob/master/main.ls#L16 i.e. https://github.com/me-box/databox-twitter-driver/blob/master/options.json).

The extra advantage here is that we would have a way of allowing developers to have per-endpoint permissions. The arbiter, knowing hypercat, can query a driver for all it's available resources, and mint per-endpoint tokens, with additional granularity specs that would be specified in item metadata. Two birds, one stone. Thoughts?

> Types of sensors

Item metadata + search

> Types of actuators

Item metadata + search

> Sensors / Actuators themselves and metadata including, vendor_id, databox_id, location etc.

Item metadata + search

**Comment by Toshbrown** [comment]
Sounds good to me. 

I think it also makes sense for the arbiter to be the authoritative source of the sensor/actuator information. All apps/drivers/store have access to the arbiter already.

@yousefamar are you planning to implement this?

**Comment by ghost** [comment]
All sounds sensible to me, just don't do it in live script 😂.

**Comment by haddadi** [comment]
all, 

I'm catching these discussions in the specifications , specifically under 003-application.md and 004-arbiter.md 

Please update the specs accordingly based on progress in deployment. I suggest Yousef and you giving it a first go for the mobile sensing access to test for different sensor types (and perhaps an actuator) and report back in December meeting if this is feasible.

**Comment by yousefamar** [comment]
Thanks, will do! There are some things I wanted to hear you guys' opinions on:
1. Turns out those libs above that I linked to are super outdated. Even all the documentation, YouTube videos, Powerpoint presentations, all outdated (and last commits years ago). Even the example "cat-server" uses [v1.1 of the Hypercat specs](https://hypercatiot.github.io/spec1.1.pdf). There are some unofficial forks, but most of them only make the libs compliant with v2.0 of the specs (edit: correction: [one server implementation](https://github.com/HyperCatIoT/hc2-server) is up to 3.0 even though the name says 2, and Thingful has a 3.0 [client implementation in Go](https://github.com/thingful/hypercat-go)).
   
   The latest version of the specs from February this year, [v3.0](http://www.hypercat.io/uploads/1/2/4/4/12443814/hypercat_specification_3.00rc1-2016-02-23.pdf), is IMO much better to use, but is not backwards-compatible (though it's just some field names that have changed). This in itself is not a problem (both client and server side are really, really easy to implement from scratch) but basically, for developers, my "barrier to entry" comment might have been jumping the gun a bit.
   
   So IMO we should stick to the latest Hypercat specs, specifically what they published in May this year as [PAS 212:2016](http://shop.bsigroup.com/forms/PASs/PAS-212-2016-download/) ([get past paywall here](http://shop.bsigroup.com/upload/276778/PAS_212.pdf)) as it seems to me the most complete, so that's what I'm doing. Do we want to support those old libraries too? Or should we just point our developers to the latest specs and tell them how we implement them? Maybe that will make people update the libs across languages too.
2. Hypercat specs do include some info on authorisation under "security extensions", but it's very shallow. According to the specs, "How keys are generated, distributed and mapped to permissions in a server is implementation-specific and out of scope of this PAS" which is super cool since we can just slap on our token system!! So this means that we can automatically also stop apps from looking at catalogues they have no business looking at using the same system as for data.
   
   According to specs, keys can either be passed with HTTP basic auth (key as username, empty string as password) or through a header. I find doing it with basic auth is kind of weird, but the header makes sense, so I propose that for everything else, we no longer pass tokens/macaroons as extra request variables, but instead as HTTP headers, and that way apps can just have their tokens in headers for both catalogues and data.
3. Something that we might still need to think through some more: Once all of this works, there's no requirement for apps to need to know about drivers beforehand. We should modify manifest permission specs to indicate a _type of data_ (an extension of RFC2046 MIME like Hypercat) rather than driver. I think this could be pretty powerful, i.e. driver manufacturers conforming to hypercat specs can now say "I make temperature data available in this format", and apps can say "I consume temperature data in this format" and it doesn't matter if the driver is driver-phillips-thermometer or driver-nest-thermostat or driver-mobile/battery-temp. Deciding which is picked is up to the user, based on which makes sense and other factors (owner, location, etc).
   
   Edit: forgot to mention, this would also mean that a user browsing an app store can now access much more stuff since they're much more likely to e.g. have a _thing with temperature_ than to have a _Phillips SmartThermometer v2_ which was anyway part of the philosophy behind Hypercat. The arbiter (or a separate discovery-type container) could hold the root catalogue of every resource in the Databox, and it can be searched for things that work against an app manifest, before the app is downloaded. (The store could also just filter those out by default).

**Comment by dominicjprice** [comment]
Re: point 3, I strongly agree that this should be the approach.

**Comment by haddadi** [comment]
great, all sounds good, for now please let's assess the feasibility of hypercat itself, not the forks :)

no point worrying about legacy support at the moment, at this stage (of project, and IoT as a whole) we should reason backward but look forward. The developer community should catch up with the new standards. 

having HTTP API queries makes sense for most services.

I'm updating the specs this week according to all the launch discussions, will hopefully handover to you all by the weekend..

**Comment by Toshbrown** [comment]
I to agree with point 3 and to going with the v3 spec.

To try and get my head around how this might work I have handcrafted a hypercat catalogue for the databox-driver-os-monitor. It looks like this:

```
    {
        "catalogue-metadata":[
            {
                "rel":"urn:X-hypercat:rels:isContentType",
                "val":"application/vnd.hypercat.catalogue+json"
            },
            {
                "rel":"urn:X-hypercat:rels:hasDescription:en", 
                "val":"databox-driver-os-monitor"
            }
        ],
        "items":[
            {
                "href":"http://databox-driver-os-monitor-databox-datastoer-timeseries:8080/api/loadavg1",
                "item-metadata":[
                    {
                    "rel":"urn:X-hypercat:rels:hasDescription:en",
                    "val":"load average over 1 minute",
                    }
                ]
            },
            {
                "href":"http://databox-driver-os-monitor-databox-datastoer-timeseries:8080/api/loadavg5",
                "item-metadata":[
                    {
                    "rel":"urn:X-hypercat:rels:hasDescription:en",
                    "val":"load average over 5 minutes",
                    }
                ]
            },
            {
                "href":"http://databox-driver-os-monitor-databox-datastoer-timeseries:8080/api/loadavg15",
                "item-metadata":[
                    {
                    "rel":"urn:X-hypercat:rels:hasDescription:en",
                    "val":"load average over 15 minute",
                    }
                ]
            },
            {
                "href":"http://databox-driver-os-monitor-databox-datastoer-timeseries:8080/api/freemem",
                "item-metadata":[
                    {
                    "rel":"urn:X-hypercat:rels:hasDescription:en",
                    "val":"free memory in bytes",
                    }
                ]
            }
            ]
    }
```

Does this seem reasonable? 

There are a few things that the above ignores:
1. how do we describe actuators?
2. the hrefs point to an API endpoint for each sensor should the API be described in the metadata? e.g urn:databox:api-type val:timeseries
3. how do we deal with historical data?
4. do we need a urn:databox:sensor-type and urn:databox:unit and urn:databox:location to enable point 3

Apologies for the brain dump.

**Comment by yousefamar** [comment]
Yes, exactly! The above catalogue would be hosted by the driver `databox-driver-os-monitor`, and queried via a store. The arbiter would host a "root" catalogue that has all of these listed as nested catalogues (also `application/vnd.hypercat.catalogue+json`). I have the arbiter building the item array on the fly based on what is querying (with token in `x-api-key` header).

The items would also describe in `item-metadata` what kind of data they make available. So if a driver makes _temperature_ data available in _CSV_, then anything that can consume _temperature_ data in _CSV_ can use that. More general info on ontology [here](http://wiki.1248.io/doku.php#what_metadata_should_i_use) but it will probably be something MIME-y anyway.

I'm in the process of writing more documentation (and code) and will push to the docs repo soon.

> how do we describe actuators?

The "root" catalogue would not describe actuators except for maybe indicating if a driver is a driver or an actuator or both etc. Actuators would also be described in the leaf catalogues and would work the same way as data sources in that they indicate the API, format, and other metadata.

> the hrefs point to an API endpoint for each sensor should the API be described in the metadata? e.g urn:databox:api-type val:timeseries

Not in the catalogue for this driver, but in the root catalogue that points to all of the other catalogues. The API should be consistent across all kinds of stores though (i.e. just HTTP requests), it's just the format of the data that comes out, and it's context that need to be specified (e.g. a CSV stream of temperature data, or a JSON document of your profile). And it shouldn't matter at that level whether it's a time-series store or a document store.

> how do we deal with historical data?

This system would be indifferent to that in the sense that it's implementation specific. One solution could be for example that an endpoint takes additional parameter that define a range of time or a number of entries, and then it sends all those and may or may not continue streaming new JSON objects or CSV  lines or whatever. This would however be a new "MIME type" rather than the normal types, so it would be part of figuring out a good ontology for people to agree how these different endpoints work and how they should interact with them.

> do we need a urn:databox:sensor-type and urn:databox:unit and urn:databox:location to enable point 3

Not sure how it's related to point 3, but you would certainly need metadata like that for the dashboard for differentiating between the thermometer in your kitchen vs the one in your garden etc. (just like what's happening already). But yeah, we would need to figure out a [naming scheme](http://martinfowler.com/bliki/TwoHardThings.html) for those things.

**Comment by yousefamar** [comment]
Ah, you mean my point 3. The way I was going to deal with that was by not even making the other sensors visible to the querying app. So in other words, if you had two thermometers, and you decide to let an app only access one, then on top of token auth, it won't even see the second one when it walks the catalogues.

On the other hand, it could be that you want to allow an app to access "all thermometers in my house" and in that case it would indeed have to use metadata to differentiate between them. Actually even if you give it access to two. I might be that at that point if an app wants anything more specific that it would need some UI for the user to go in and say "kitchen thermometer is the one that triggers a fire alarm at 10 degrees C, and garden thermometer at 20 degrees C", if your app triggers alarms based on thermometer readings and needs to know the difference.

It would help to do what you said though -- agreeing on metadata tags for location etc that the apps can understand universally, and making those the standard.

Edit: Also in many cases some metadata tags will be specific to the data/endpoints, e.g. if the temperature endpoint gives Celsius or Fahrenheit or even Kelvin or whatever.
